.TH MYCAT 3 "23 September 2025" "v0.4.1-final" "Client Application Manual"
.SH NAME
mycat \- A simple client program for demonstrating man pages

.SH SYNOPSIS
client_dynamic [options] [file ...]

.SH DESCRIPTION
mycat is a demonstration client program that implements string and file
utilities. It can read files, perform string operations, and display results
to standard output.

.SH AUTHOR
Aaliyan Asim 
